http:
  port: 1337
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  weather:
    host: localhost
    paths: '/api/weather/*'
  doodle:
    host: localhost
    paths: '/api/*'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  weather:
    url: 'http://localhost:8081'
  doodle:
    url: 'http://localhost:8080'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  weather:
    apiEndpoints:
      - weather
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl} 
      - proxy:
          - action:
              serviceEndpoint: weather 
              changeOrigin: true
  doodle:
    apiEndpoints:
      - doodle
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl} 
      - proxy:
          - action:
              serviceEndpoint: doodle 
              changeOrigin: true
